---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

cache:
  yarn: true

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

install:
  - yarn install --frozen-lockfile

script:
  - yarn test
  - yarn lint
  - yarn build
